spring.application.name=cartapi

spring.datasource.url=jdbc:mysql://localhost:3306/cartapi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sql123

spring.jpa.show-sql=true

spring.liquibase.enabled=false
spring.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jwt.secret = kmpeahufnaipvjtfudxtgcuynqmftymd
# 24hrs: 86400 seconds
spring.jwt.accessTokenExpiration = 86400
# 7d: 604800 seconds
spring.jwt.refreshTokenExpiration = 604800